'Khao Phad Mhoo':['rice','pork','egg','soy sauce','oyster sauce'],
'Khao Phad Ghai':['rice','chicken','egg','soy sauce','oyster sauce'],
'Mhoo Thord Kratiem':['pork','garlic'],
'Ghai Thord Kratiem':['chicken','garlic'],
'Mhoo Phad Kra Phrao':['pork','basil','chilli','garlic','oyster sauce'],
'Ghai Phad Kra Phrao':['chicken','basil','chilli','garlic','oyster sauce'],
'Mama Phad Mhoo':['mama','pork','egg'],
'Mama Phad Ghai':['mama','chicken','egg'],
'Mhoo Thord Nam Plar':['pork','fish sauce'],
'Ghai Thord Nam Plar':['chicken','fish sauce'],
'Panaeng Mhoo':['pork','panaeng curry','coconut milk','red chilli'],
'Panaeng Ghai':['chicken','panaeng curry','coconut milk','red chilli'],
'Fak Tong Phad Khai':['pumpkin','egg','garlic'],
'Khai Palo':['egg','tofu','palo','garlic'],
'Khai Jiew Mhoo Sahb':['egg','pork','soy sauce'],
'Mhoo Phad Nammun Hoy':['pork','oyster sauce','garlic'],
'Mhoo Phad Phonk Kraree':['pork','curry powder','onion','milk','egg'],
'Phad Prick Gaenk Mhoo':['pork','curry'],
'Phad Phonk Kraree Thale':['squid','shrimp','onion','milk','egg','curry powder'],
'Khaw Thom Mhoo':['pork','rice'],
'Khaw Thom Koong':['shrimp','rice'],
'Masman Ghai':['chicken','onion','coconut milk','potato','masman curry'],
'Mhoo Manaw':['pork','garlic','red chilli','fish sauce','lemon'],
'Tom Yam Koong Nam Khon':['mushroom','milk','shrimp','chili paste','chilli','lemon','tomato'],
'Suki Mhoo':['garlic','egg','pork','suki sauce'],
'Larb Mhoo':['pork','shallot','coriander','chilli','lemon'],
'Larb Ghai':['chicken','shallot','coriander','chilli','lemon'],
'Tom Jued Mhoo Sub':['pork','tofu','soup cube'],
'Hed Phud Nammun Hoy':['mushroom','oyster sauce','soy sauce'],
'Khaw Thom Plar':['fish','rice'],
'Khana Mhoo':['pork','kale','soy sauce','oyster sauce'],
'Mhoo Phad Prick Phao':['pork','chili paste'],
'Ghai Phad Prick Phao':['chicken','chili paste'],
'Makuer Phad Khai':['egg','tomato'],
'Gaenk Som Mhoo':['pork','curry','chilli','shrimp paste'],
'Ghai Thom Nam plar':['chicken','fish sauce','soy sauce'],


